---

#- hosts: all
 # become: true
  #tasks:

 # - name: update repository index
  #  apt:
   #   update_cache: yes
   # when: ansible_distribution == "Ubuntu"
 # - name: install apache2 package
  #  apt:
   #   name: apache2
   #   state: latest
   # when: ansible_distribution == "Ubuntu"


#- hosts: all
 # become: true
  #tasks:

  #- name: install apache2 and php packages for Ubuntu
   # apt:
    #  name:
     #   - apache2
      #  - libapache2-mod-php
     # state: latest
     # update_cache: yes
#    when: ansible_distribution == "Ubuntu"

 # - name: install apache and php packages for CentOS
  #  dnf:
   #   name:
    #    - httpd
     #   - php
     # state: latest
     # update_cache: yes
    # when: ansible_distribution == "CentOS"


- hosts: all
  become: true
  tasks:

  - name: install apache and php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
